const records=[];
    let tagColors={};
    const tagCatalog=[];
    const tagPalette=["#b69aac","#9586c8","#6d7fa9","#7193a0","#8fa780","#b7a66c","#c98262","#c66470"];
    const compactMedia=matchMedia("(max-width: 900px)");
    const state={query:"",filter:"All",selected:new Set(),activeId:null,activeNoteId:null,sortRecent:true,galleryMode:"waterfall",theme:matchMedia("(prefers-color-scheme: light)").matches?"light":"dark",searchOpen:false,tagPickerOpen:false,tagQuery:"",tagPickerPosition:null,lastAction:"",inspectorMode:"closed",inspectorPosition:null,sidebarOpen:!compactMedia.matches,sidebarTagQuery:"",selectedSidebarTags:new Set(),lastSidebarTagIndex:null,sidebarTagMenu:null,sidebarTagEditor:null};
    let tagOrder=[];
    const saveTimers=new Map();
    let metadataReloading=false;
    let metadataReloadStatus="";
    function recordFromStored(record){return{id:record.pinId,title:`Pin ${record.pinId}`,tags:PinRefStore.normalizeTags(record.tags),note:record.note||"",saved:new Date(record.savedAt).toLocaleDateString(),savedAt:record.savedAt,previewUrl:record.previewUrl||null,url:record.url||`https://www.pinterest.com/pin/${record.pinId}/`,ratio:"4/5"};}
    function rebuildTagCatalog(){const counts=new Map();records.forEach(record=>record.tags.forEach(tag=>counts.set(tag,(counts.get(tag)||0)+1)));const ordered=[...counts].map(([tag,count])=>({tag,count})).sort((a,b)=>{const ai=tagOrder.indexOf(a.tag),bi=tagOrder.indexOf(b.tag);if(ai>=0||bi>=0)return(ai<0?Infinity:ai)-(bi<0?Infinity:bi);return b.count-a.count||a.tag.localeCompare(b.tag);});tagCatalog.splice(0,tagCatalog.length,...ordered);}
    function persistRecord(record){clearTimeout(saveTimers.get(record.id));saveTimers.set(record.id,setTimeout(()=>{saveTimers.delete(record.id);PinRefStore.updateRecord(record.id,{tags:record.tags,note:record.note});},160));}
    function persistRecords(items){items.forEach(record=>PinRefStore.updateRecord(record.id,{tags:record.tags,note:record.note}));}
    function persistTagSettings(){PinRefStore.updateSettings({tagColors,tagOrder});}
    function updateMetadataReloadControl(){const control=document.querySelector("#metadata-reload-control"),button=document.querySelector("#reload-dashboard-metadata"),status=document.querySelector("#metadata-reload-status");if(!control||!button||!status)return;button.disabled=metadataReloading||!state.selected.size;control.classList.toggle("loading",metadataReloading);control.style.right=!compact()&&state.inspectorMode==="docked"?"390px":"14px";status.textContent=metadataReloadStatus;}
    async function reloadSelectedMetadata(){const pinIds=[...state.selected];if(!pinIds.length||metadataReloading)return;metadataReloading=true;metadataReloadStatus=`Reloading ${pinIds.length} selected Pin${pinIds.length===1?"":"s"}…`;updateMetadataReloadControl();try{const response=await chrome.runtime.sendMessage({type:"pinref:reloadMetadata",pinIds});const refreshed=response?.results?.filter(result=>result.ok)||[];const previewCount=refreshed.filter(result=>result.refreshed?.preview).length;metadataReloadStatus=response?.ok?`Reloaded ${refreshed.length}/${pinIds.length} · ${previewCount} preview`:response?.message||"Reload failed.";await loadLibrary(true);}catch{metadataReloadStatus="Reload failed. Open the Pin on Pinterest and try again.";}finally{metadataReloading=false;updateMetadataReloadControl();}}
    const esc=value=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
    const compact=()=>compactMedia.matches;
    const activeRecord=()=>records.find(record=>record.id===state.activeId)||records[0];
    const selectedRecords=()=>records.filter(record=>state.selected.has(record.id));
    const contextRecords=()=>selectedRecords();
    function intersectionTags(items){return items.length?items[0].tags.filter(tag=>items.every(item=>item.tags.includes(tag))):[];}
    function filteredRecords(){const q=state.query.trim().toLowerCase();const list=records.filter(r=>{const haystack=[r.id,r.title,r.note,...r.tags].join(" ").toLowerCase();const filterMatch=state.filter==="All"||(state.filter==="Recent"&&Date.now()-Date.parse(r.savedAt)<=604800000)||(state.filter==="Untagged"&&!r.tags.length)||(state.filter!=="Trash"&&r.tags.includes(state.filter));return(!q||q.split(/\s+/).every(token=>haystack.includes(token)))&&filterMatch;}).sort((a,b)=>String(b.savedAt).localeCompare(String(a.savedAt)));return state.sortRecent?list:[...list].reverse();}
    function tagHTML(tag){return `<span class="tag" style="--tag-color:${tagColors[tag]||"#8f91a0"}">${esc(tag)}</span>`;}
    function artHTML(record,className=""){return record.previewUrl?`<img class="art real-art ${className}" style="--ratio:${record.ratio}" src="${esc(record.previewUrl)}" alt="">`:`<div class="art real-placeholder ${className}" style="--ratio:${record.ratio}" role="img" aria-label="No preview available"><span>No preview</span></div>`;}
    function masonrySpan(ratio){const [width,height]=ratio.split("/").map(Number);return Math.max(10,Math.round(((180*height/width)+12)/18));}
    function cardHTML(record){const selected=state.selected.has(record.id)?" selected":"";return `<article class="ref-card${selected}" style="--card-ratio:${record.ratio};--masonry-span:${masonrySpan(record.ratio)}" data-id="${record.id}" tabindex="0" aria-label="${esc(record.title)}"><button class="select-box" data-select="${record.id}" aria-label="Toggle selection for ${esc(record.title)}"></button>${artHTML(record,"card-art")}</article>`;}
    function detailHTML(record){return `<div class="detail-content">${artHTML(record,"detail-image")}<div><div class="eyebrow">Saved reference</div><h2 style="margin:6px 0 4px;font-size:19px">${esc(record.title)}</h2><span class="muted" style="font-size:12px">pinterest.com/pin/${record.id}</span></div><div class="divider"></div><section class="detail-section"><h3>Note</h3>${noteEditorHTML(record)}</section>${editableTagsHTML([record])}<div class="divider"></div><dl class="detail-grid"><dt>Added</dt><dd>${esc(record.saved)}</dd><dt>Status</dt><dd><span style="color:#72d39d">●</span> Saved</dd></dl><a class="open-source-button" href="${esc(record.url)}" target="_blank" rel="noreferrer">Open on Pinterest <span aria-hidden="true">↗</span></a></div>`;}
    function searchHTML(){const counts=[...new Set(records.flatMap(r=>r.tags))].map(tag=>({tag,count:records.filter(r=>r.tags.includes(tag)).length})).sort((a,b)=>b.count-a.count||a.tag.localeCompare(b.tag));const visible=state.query?counts.filter(item=>item.tag.includes(state.query.toLowerCase())):counts;const popover=state.searchOpen?`<div class="search-suggestions"><div class="suggestion-heading"><strong>Suggested tags</strong><span>Search notes and boards too</span></div>${visible.map(item=>`<button class="suggestion-item" data-search-tag="${esc(item.tag)}"><i style="--item-color:${tagColors[item.tag]||"#8f91a0"}"></i><span>${esc(item.tag)}</span><small>${item.count} refs</small></button>`).join("")||`<div class="suggestion-heading"><span>No matching tags</span></div>`}</div>`:"";return `<div class="search-box"><span>⌕</span><input id="search" name="reference-search" value="${esc(state.query)}" placeholder="Search tags, notes, boards, or anything…" aria-label="Search references" autocomplete="off"><kbd>⌘ K</kbd>${popover}</div>`;}
    function filteredSidebarTags(){const q=state.sidebarTagQuery.trim().toLowerCase();return tagCatalog.filter(item=>!q||item.tag.includes(q));}
    function sidebarManagerHTML(){const editor=state.sidebarTagEditor;if(editor){const tags=editor.tags||[],label=tags.length===1?tags[0]:`${tags.length} tags`;if(editor.mode==="rename")return `<div class="sidebar-manage-card" role="dialog" aria-label="Rename ${esc(label)}"><header><strong>Rename ${esc(label)}</strong><button data-close-tag-manager aria-label="Close">×</button></header><input class="tag-editor-input" id="tag-rename-input" name="tag-name" autocomplete="off" value="${esc(tags[0])}" aria-label="New tag name"><div class="tag-editor-footer"><button data-close-tag-manager>Cancel</button><button data-save-tag-name>Save</button></div></div>`;if(editor.mode==="color")return `<div class="sidebar-manage-card" role="dialog" aria-label="Change ${esc(label)} color"><header><strong>Marker color</strong><button data-close-tag-manager aria-label="Close">×</button></header><div class="color-swatches">${tagPalette.map(color=>`<button class="color-swatch${tagColors[tags[0]]===color?" active":""}" style="--swatch:${color}" data-set-tag-color="${color}" aria-label="Use ${color}"></button>`).join("")}</div></div>`;return `<div class="sidebar-manage-card" role="alertdialog" aria-label="Remove ${esc(label)}"><header><strong>Remove ${esc(label)}?</strong><button data-close-tag-manager aria-label="Close">×</button></header><p class="tag-editor-copy">This removes ${tags.length===1?"the tag":"these tags"} from the sidebar and every saved Pin. This prototype cannot undo it.</p><div class="tag-editor-footer"><button data-close-tag-manager>Cancel</button><button class="danger" data-remove-sidebar-tags>Remove</button></div></div>`;}if(state.sidebarTagMenu)return `<div class="sidebar-manage-card"><header><span class="tag-dot" style="--tag-color:${tagColors[state.sidebarTagMenu]||"#8f91a0"}"></span><strong>${esc(state.sidebarTagMenu)}</strong><button data-close-tag-manager aria-label="Close">×</button></header><div class="tag-manage-actions"><button data-edit-sidebar-tag="rename">✎ Rename</button><button data-edit-sidebar-tag="color">● Marker color</button><button class="danger" data-edit-sidebar-tag="delete">⌫ Remove tag</button></div></div>`;return"";}
    function sidebarHTML(){const tags=filteredSidebarTags();const item=(icon,label,count,filter,active=state.filter===filter)=>`<button class="sidebar-item${active?" active":""}" data-sidebar-filter="${esc(filter)}"><span class="sidebar-icon">${icon}</span><span>${esc(label)}</span><em>${count}</em></button>`;const heading=state.selectedSidebarTags.size?`<div class="sidebar-selection-head"><strong>${state.selectedSidebarTags.size} selected</strong><button class="danger" data-bulk-remove-tags aria-label="Remove selected tags">⌫ Remove</button><button data-clear-sidebar-selection aria-label="Clear tag selection">×</button></div>`:`<span class="sidebar-heading-title">Tags <em class="sidebar-heading-count">${tagCatalog.length}</em></span><button aria-label="Create tag">＋</button>`;return `<aside class="library-sidebar" aria-label="Library navigation"><div class="sidebar-brand"><span class="sidebar-brand-copy"><strong>PinRef</strong></span></div><nav>${item("▣","All Pins",records.length,"All")}${item("◷","Recently Added",records.filter(r=>Date.now()-Date.parse(r.savedAt)<=604800000).length,"Recent")}${item("⬡","Untagged",records.filter(r=>!r.tags.length).length,"Untagged")}${item("♲","Trash",0,"Trash")}<section class="sidebar-section tags-section"><div class="sidebar-heading">${heading}</div><label class="sidebar-tag-search"><span>⌕</span><input id="sidebar-tag-search" name="sidebar-tag-search" autocomplete="off" value="${esc(state.sidebarTagQuery)}" placeholder="Filter tags…" aria-label="Filter tags"></label><div class="sidebar-tag-list" aria-label="Tag list">${tags.map(({tag,count},index)=>`<div class="sidebar-tag-item${state.filter===tag?" active":""}${state.selectedSidebarTags.has(tag)?" checked":""}" draggable="true" data-sidebar-tag-row="${esc(tag)}" data-sidebar-tag-index="${index}"><button class="tag-drag-handle" aria-label="Drag ${esc(tag)} to reorder">⠿</button><label class="tag-check"><input type="checkbox" ${state.selectedSidebarTags.has(tag)?"checked":""} data-sidebar-tag-check="${esc(tag)}" aria-label="Select ${esc(tag)}"></label><button class="sidebar-tag-filter" data-sidebar-filter="${esc(tag)}"><span class="tag-dot" style="--tag-color:${tagColors[tag]||"#8f91a0"}"></span><span>${esc(tag)}</span></button><em class="sidebar-tag-count">${count}</em><button class="tag-more" data-sidebar-tag-menu="${esc(tag)}" aria-label="Manage ${esc(tag)}">•••</button></div>`).join("")||`<div class="sidebar-more">No matching tags</div>`}</div>${sidebarManagerHTML()}</section></nav><div class="sidebar-footer">${themeButton()}<button class="sidebar-footer-button donation" data-donation><span>☕</span><span><strong>Support PinRef</strong><small>Donation details coming later</small></span></button></div></aside><button class="sidebar-backdrop" data-sidebar-backdrop aria-label="Close sidebar"></button>`;}
    function themeButton(){const next=state.theme==="light"?"dark":"light";return `<button class="sidebar-footer-button" id="theme" title="Switch to ${next} theme" aria-label="Switch to ${next} theme"><span>${state.theme==="light"?"☀":"☾"}</span><span><strong>${state.theme==="light"?"Light":"Dark"} theme</strong><small>Switch to ${next}</small></span></button>`;}
    function layoutIcon(mode){if(mode==="waterfall")return `<svg viewBox="0 0 16 16" aria-hidden="true"><rect x="2" y="2" width="5" height="8" rx="1.2"/><rect x="9" y="2" width="5" height="5" rx="1.2"/><rect x="2" y="12" width="5" height="2" rx="1"/><rect x="9" y="9" width="5" height="5" rx="1.2"/></svg>`;return `<svg viewBox="0 0 16 16" aria-hidden="true"><rect x="2" y="2" width="5" height="5" rx="1.2"/><rect x="9" y="2" width="5" height="8" rx="1.2"/><rect x="2" y="9" width="5" height="5" rx="1.2"/><rect x="9" y="12" width="5" height="2" rx="1"/></svg>`;}
    function galleryControlsHTML(){const modes=[{id:"masonry",label:"Masonry",hint:"Dense row-first packing"},{id:"waterfall",label:"Waterfall",hint:"Balanced vertical columns"}];return `<div class="layout-switcher" role="group" aria-label="Gallery layout">${modes.map(mode=>`<button class="layout-option${state.galleryMode===mode.id?" active":""}" data-gallery-mode="${mode.id}" aria-pressed="${state.galleryMode===mode.id}" title="${mode.hint}">${layoutIcon(mode.id)}<span class="layout-label">${mode.label}</span></button>`).join("")}</div>`;}
    function tagPickerHTML(){if(!state.tagPickerOpen)return"";const all=[...new Set(records.flatMap(r=>r.tags))];const applied=intersectionTags(contextRecords());const query=state.tagQuery.trim().toLowerCase();const matches=all.filter(tag=>tag.includes(query)).slice(0,12);const canCreate=query&&!all.includes(query);const status=state.lastAction||`${applied.length} tag${applied.length===1?"":"s"} applied`;return `<button class="tag-picker-scrim" data-close-tag-picker aria-label="Close tag picker"></button><div class="toolbar-popover tag-picker" role="dialog" aria-modal="false" aria-label="Add tags"><div class="tag-picker-head" data-drag-handle="tag-picker"><div><strong style="font-size:12px">Add tags</strong><div class="muted" style="font-size:9px;margin-top:1px">Drag this title bar to move</div></div><button class="icon-button" data-close-tag-picker aria-label="Close tag picker">×</button></div><input id="tag-picker-search" name="tag-search" autocomplete="off" role="combobox" aria-label="Search or create a tag" aria-expanded="true" aria-controls="tag-options" aria-autocomplete="list" value="${esc(state.tagQuery)}" placeholder="Search or create…"><div class="tag-picker-status" aria-live="polite"><strong>${esc(status)}</strong><div class="tag-picker-status-tags">${applied.map(tag=>`<span>${esc(tag)}</span>`).join("")||`<span>No shared tags yet</span>`}</div></div><div id="tag-options" class="tag-picker-list" role="listbox"><div class="tag-section-label">${query?"Matches":"Recommended"}</div>${matches.map(tag=>{const isApplied=applied.includes(tag);return `<button class="tag-option${isApplied?" applied":""}" role="option" aria-selected="${isApplied}" ${isApplied?"disabled":""} data-apply-tag="${esc(tag)}"><i style="--item-color:${tagColors[tag]||"#8f91a0"}"></i><span>${esc(tag)}</span><small>${isApplied?"✓ Added":`${records.filter(r=>r.tags.includes(tag)).length} refs`}</small></button>`;}).join("")}${canCreate?`<button class="tag-option" role="option" data-create-tag="${esc(query)}"><i style="--item-color:${tagColors[query]||"#8f91a0"}"></i><span>Create “${esc(state.tagQuery.trim())}”</span><small>New tag</small></button>`:""}</div><div class="tag-picker-footer"><button class="quiet-button primary" data-close-tag-picker>Done</button></div></div>`;}
    function contextVisualHTML(items){if(items.length===1)return artHTML(items[0],"summary-art");return `<div class="stacked-thumbnails" aria-label="${items.length} selected reference thumbnails">${items.slice(0,3).map(item=>artHTML(item,"stack-art")).join("")}</div>`;}
    function editableTagsHTML(items){const common=intersectionTags(items);return `<section class="detail-section"><h3>${items.length>1?"Shared tags":"Tags"}</h3><div class="editable-tag-row">${common.map(tag=>`<span class="editable-tag">${esc(tag)}<button data-remove-common-tag="${esc(tag)}" aria-label="Remove ${esc(tag)} tag">×</button></span>`).join("")||`<span class="muted" style="font-size:11px">No shared tags</span>`}<button class="add-tag-round" data-toggle-tag-picker aria-label="Add tag">＋</button></div></section>`;}
    function noteEditorHTML(record){return `<textarea class="note-editor" name="note-${record.id}" data-note-editor="${record.id}" aria-label="Edit note for ${esc(record.title)}" placeholder="Add a note…">${esc(record.note)}</textarea>`;}
    function notePreviewHTML(items){const notes=items;if(items.length===1)return `<section class="detail-section"><h3>Note</h3>${noteEditorHTML(notes[0])}</section>`;const active=notes.find(item=>item.id===state.activeNoteId)||notes[0];return `<section class="detail-section"><h3>Notes in selection</h3><div class="selection-notes"><div class="note-tabs" role="tablist" aria-label="Selected Pin notes">${notes.map(item=>`<button class="note-tab${item.id===active.id?" active":""}" role="tab" aria-selected="${item.id===active.id}" data-note-id="${item.id}"><strong>${esc(item.title)}</strong><span>${esc(item.note)||"No note yet"}</span></button>`).join("")}</div><article class="note-full"><strong data-note-full-title>${esc(active.title)}</strong>${noteEditorHTML(active)}</article></div></section>`;}
    function multiDetailsHTML(items){if(items.length===1)return detailHTML(items[0]);return `<div class="detail-content"><div class="selection-overview">${contextVisualHTML(items)}<div class="selection-overview-copy"><div class="eyebrow">Selection</div><h2>${items.length} Pins selected</h2><p>Bulk metadata and shared fields</p></div></div><div class="divider"></div>${editableTagsHTML(items)}${notePreviewHTML(items)}<section class="detail-section"><h3>Selected references</h3>${items.map(item=>`<div class="note-preview"><strong>${esc(item.title)}</strong><p>${esc(item.saved)}</p></div>`).join("")}</section></div>`;}
    function inspectorStyle(){if(state.inspectorMode!=="floating"||!state.inspectorPosition)return"";return `left:${state.inspectorPosition.x}px;top:${state.inspectorPosition.y}px;right:auto;bottom:auto;`;}
    function inspectorHTML(){if(state.inspectorMode==="closed")return"";const items=contextRecords(),hasItems=items.length>0;if(!hasItems&&state.inspectorMode!=="docked")return"";const multi=items.length>1,title=hasItems?(multi?`${items.length} Pins selected`:items[0].title):"Inspector",emptyClass=hasItems?"":" empty",draggable=state.inspectorMode==="floating",selectionLabel=hasItems?`${items.length} selected`:"No selection";const dockIcon=`<svg viewBox="0 0 20 20" aria-hidden="true"><rect x="2.75" y="3.25" width="14.5" height="13.5" rx="2.5"></rect><path d="M12 3.75v12.5"></path></svg>`;const controls=`<button class="panel-toolbar-button" data-toggle-dock aria-label="${state.inspectorMode==="docked"?"Undock":"Dock"} inspector" title="${state.inspectorMode==="docked"?"Undock":"Dock"}">${dockIcon}</button>${state.inspectorMode==="floating"?`<button class="panel-toolbar-button" data-close-inspector aria-label="Close inspector" title="Close">×</button>`:""}`;const quickBody=`<div class="selection-overview">${contextVisualHTML(items)}<div class="selection-overview-copy"><div class="eyebrow">${multi?"Selected references":"Saved reference"}</div><h2>${esc(title)}</h2><p>${multi?`${items.length} items · shared metadata`:items[0].saved}</p></div></div><div class="divider" style="margin:12px 0"></div>${editableTagsHTML(items)}<div style="height:12px"></div>${notePreviewHTML(items)}`;const body=!hasItems?`<div class="inspector-empty"><div class="inspector-empty-icon">◇</div><strong>Select a Pin</strong><p>The dock stays available. Select one or more references to inspect tags and notes.</p></div>`:`${state.inspectorMode==="docked"?multiDetailsHTML(items):quickBody}<div class="inspector-actions"><button class="inspector-clear" data-clear-selection>Clear selection</button></div>`;return `<aside class="inspector-panel ${state.inspectorMode}${emptyClass}" data-inspector style="${inspectorStyle()}" aria-label="Inspector"><header class="panel-titlebar${draggable?" draggable-titlebar":""}" ${draggable?`data-drag-handle="inspector" title="Drag to move Inspector"`:""}><div class="panel-heading"><strong>Inspector</strong><small>${selectionLabel}</small></div><span class="spacer"></span>${controls}</header><div class="inspector-body">${body}</div></aside>`;}
    function galleryHTML(list){if(!records.length)return`<div class="dashboard-empty"><span>◇</span><strong>Your local library is empty</strong><p>Use Pinterest’s own Save button. PinRef will mirror saved Pins into this local library.</p></div>`;if(!list.length)return`<div class="dashboard-empty"><span>⌕</span><strong>No matching references</strong><p>Try another search or tag filter.</p></div>`;return list.map(cardHTML).join("");}
    function render(){const list=filteredRecords(),docked=!compact()&&state.inspectorMode==="docked";document.getElementById("app").innerHTML=`<div class="workspace ${state.sidebarOpen?"":"sidebar-closed"} ${docked?"inspector-docked-layout":""}">${sidebarHTML()}<div class="anchored-topbar"><button class="sidebar-toggle" data-sidebar-toggle aria-label="${state.sidebarOpen?"Hide":"Show"} sidebar" aria-expanded="${state.sidebarOpen}"><svg class="sidebar-toggle-icon" viewBox="0 0 20 20" aria-hidden="true"><rect x="2.5" y="3" width="15" height="14" rx="2.5"></rect><path d="M7.5 3.5v13"></path></svg><span class="control-tooltip">${state.sidebarOpen?"Hide":"Show"} sidebar</span></button>${searchHTML()}</div><section class="contact ${docked?"inspector-docked":""}"><header class="contact-header"><div class="topbar-primary"></div><div class="gallery-toolbar"><div class="gallery-context"><strong>${list.length} references</strong>${state.filter!=="All"?`<span class="active-filter">Tag · ${esc(state.filter)}</span>`:""}</div><div class="gallery-controls"><button class="compact-sort" data-sort-recent aria-label="Change sort order">⇅ <span>${state.sortRecent?"Recently added":"Oldest first"}</span></button>${galleryControlsHTML()}</div></div></header><div class="contact-sheet mode-${state.galleryMode}" aria-label="Reference gallery in ${state.galleryMode} layout">${galleryHTML(list)}</div>${inspectorHTML()}</section>${tagPickerHTML()}</div>`;document.getElementById("prototype-state").textContent=`Throwaway prototype · ${state.sidebarOpen?"Sidebar open":"Sidebar closed"} · ${state.galleryMode} gallery · Inspector ${state.inspectorMode} · ${state.selected.size?`${state.selected.size} selected`:"No selection"}`;bind();}
    function applyTheme(){document.documentElement.dataset.theme=state.theme;}
    function applyTag(tag){const clean=tag.trim().toLowerCase();if(!clean)return;const items=contextRecords();items.forEach(record=>{if(!record.tags.includes(clean))record.tags.push(clean);});if(!tagOrder.includes(clean))tagOrder.push(clean);rebuildTagCatalog();persistRecords(items);persistTagSettings();state.lastAction=`Added “${clean}” to ${items.length} reference${items.length>1?"s":""}`;state.tagQuery="";render();requestAnimationFrame(()=>document.querySelector("#tag-picker-search")?.focus());}
    function removeCommonTag(tag){const items=contextRecords();items.forEach(record=>{record.tags=record.tags.filter(item=>item!==tag);});rebuildTagCatalog();persistRecords(items);state.lastAction=`Removed “${tag}”`;render();}
    function removeSidebarTags(tags){tags.forEach(tag=>{records.forEach(record=>{record.tags=record.tags.filter(item=>item!==tag);});delete tagColors[tag];tagOrder=tagOrder.filter(item=>item!==tag);if(state.filter===tag)state.filter="All";state.selectedSidebarTags.delete(tag);});rebuildTagCatalog();persistRecords(records);persistTagSettings();state.sidebarTagEditor=null;state.sidebarTagMenu=null;render();}
    function renameSidebarTag(oldTag,newValue){const next=newValue.trim().toLowerCase();if(!next||next===oldTag){state.sidebarTagEditor=null;render();return;}const item=tagCatalog.find(entry=>entry.tag===oldTag);if(!item||tagCatalog.some(entry=>entry.tag===next))return;if(tagColors[oldTag]){tagColors[next]=tagColors[oldTag];delete tagColors[oldTag];}tagOrder=tagOrder.map(tag=>tag===oldTag?next:tag);records.forEach(record=>{record.tags=record.tags.map(tag=>tag===oldTag?next:tag);});if(state.filter===oldTag)state.filter=next;if(state.selectedSidebarTags.delete(oldTag))state.selectedSidebarTags.add(next);rebuildTagCatalog();persistRecords(records);persistTagSettings();state.sidebarTagEditor=null;state.sidebarTagMenu=null;render();}
    function bindInspectorDrag(){const handle=document.querySelector('[data-drag-handle="inspector"]'),panel=document.querySelector("[data-inspector]");if(!handle||!panel||compact())return;handle.addEventListener("pointerdown",event=>{if(event.button!==0||event.target.closest("button,a,input,textarea,[role=button]"))return;event.preventDefault();const rect=panel.getBoundingClientRect(),dx=event.clientX-rect.left,dy=event.clientY-rect.top;panel.classList.add("dragging");panel.style.left=`${rect.left}px`;panel.style.top=`${rect.top}px`;panel.style.right="auto";panel.style.bottom="auto";handle.setPointerCapture(event.pointerId);const move=e=>{const x=Math.min(innerWidth-panel.offsetWidth-8,Math.max(8,e.clientX-dx));const y=Math.min(innerHeight-panel.offsetHeight-8,Math.max(8,e.clientY-dy));panel.style.left=`${x}px`;panel.style.top=`${y}px`;};const end=e=>{if(handle.hasPointerCapture(e.pointerId))handle.releasePointerCapture(e.pointerId);const final=panel.getBoundingClientRect();state.inspectorPosition={x:Math.round(final.left),y:Math.round(final.top)};panel.classList.remove("dragging");handle.removeEventListener("pointermove",move);handle.removeEventListener("pointerup",end);handle.removeEventListener("pointercancel",end);};handle.addEventListener("pointermove",move);handle.addEventListener("pointerup",end);handle.addEventListener("pointercancel",end);});}
    function positionTagPicker(){const picker=document.querySelector(".tag-picker"),trigger=document.querySelector("[data-toggle-tag-picker]");if(!picker||!trigger)return;const width=picker.offsetWidth,height=picker.offsetHeight;if(state.tagPickerPosition){const left=Math.min(innerWidth-width-12,Math.max(12,state.tagPickerPosition.x)),top=Math.min(innerHeight-height-12,Math.max(12,state.tagPickerPosition.y));picker.style.left=`${Math.round(left)}px`;picker.style.top=`${Math.round(top)}px`;picker.style.transform="none";state.tagPickerPosition={x:Math.round(left),y:Math.round(top)};return;}const anchor=trigger.getBoundingClientRect(),left=Math.min(innerWidth-width-12,Math.max(12,anchor.left));let top=anchor.bottom+8;if(top+height>innerHeight-12)top=Math.max(12,anchor.top-height-8);picker.style.left=`${Math.round(left)}px`;picker.style.top=`${Math.round(top)}px`;picker.style.transform="none";picker.style.transformOrigin=top<anchor.top?"bottom left":"top left";}
    function bindTagPickerDrag(){const handle=document.querySelector('[data-drag-handle="tag-picker"]'),panel=document.querySelector(".tag-picker");if(!handle||!panel)return;handle.addEventListener("pointerdown",event=>{if(event.button!==0||event.target.closest("button,a,input,textarea,[role=button]"))return;event.preventDefault();const rect=panel.getBoundingClientRect(),dx=event.clientX-rect.left,dy=event.clientY-rect.top;panel.classList.add("dragging");handle.setPointerCapture(event.pointerId);const move=e=>{const x=Math.min(innerWidth-panel.offsetWidth-8,Math.max(8,e.clientX-dx));const y=Math.min(innerHeight-panel.offsetHeight-8,Math.max(8,e.clientY-dy));panel.style.left=`${x}px`;panel.style.top=`${y}px`;panel.style.transform="none";};const end=e=>{if(handle.hasPointerCapture(e.pointerId))handle.releasePointerCapture(e.pointerId);const final=panel.getBoundingClientRect();state.tagPickerPosition={x:Math.round(final.left),y:Math.round(final.top)};panel.classList.remove("dragging");handle.removeEventListener("pointermove",move);handle.removeEventListener("pointerup",end);handle.removeEventListener("pointercancel",end);};handle.addEventListener("pointermove",move);handle.addEventListener("pointerup",end);handle.addEventListener("pointercancel",end);});}
    function bind(){
      updateMetadataReloadControl();
      document.querySelector("[data-sidebar-toggle]")?.addEventListener("click",()=>{state.sidebarOpen=!state.sidebarOpen;render();requestAnimationFrame(()=>document.querySelector("[data-sidebar-toggle]")?.focus());});
      document.querySelector("[data-sidebar-backdrop]")?.addEventListener("click",()=>{state.sidebarOpen=false;render();requestAnimationFrame(()=>document.querySelector("[data-sidebar-toggle]")?.focus());});
      document.querySelectorAll("[data-sidebar-filter]").forEach(el=>el.addEventListener("click",()=>{state.filter=el.dataset.sidebarFilter;state.searchOpen=false;if(compact())state.sidebarOpen=false;render();}));
      const sidebarSearch=document.querySelector("#sidebar-tag-search");sidebarSearch?.addEventListener("input",event=>{state.sidebarTagQuery=event.target.value;const cursor=event.target.selectionStart;render();const input=document.querySelector("#sidebar-tag-search");input?.focus();input?.setSelectionRange(cursor,cursor);});
      document.querySelectorAll("[data-sidebar-tag-check]").forEach(el=>el.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();const visible=filteredSidebarTags(),index=visible.findIndex(item=>item.tag===el.dataset.sidebarTagCheck),selecting=!state.selectedSidebarTags.has(el.dataset.sidebarTagCheck);if(event.shiftKey&&state.lastSidebarTagIndex!==null){const start=Math.min(state.lastSidebarTagIndex,index),end=Math.max(state.lastSidebarTagIndex,index);visible.slice(start,end+1).forEach(item=>selecting?state.selectedSidebarTags.add(item.tag):state.selectedSidebarTags.delete(item.tag));}else selecting?state.selectedSidebarTags.add(el.dataset.sidebarTagCheck):state.selectedSidebarTags.delete(el.dataset.sidebarTagCheck);state.lastSidebarTagIndex=index;state.sidebarTagMenu=null;state.sidebarTagEditor=null;render();}));
      document.querySelectorAll("[data-sidebar-tag-menu]").forEach(el=>el.addEventListener("click",event=>{event.stopPropagation();state.sidebarTagMenu=state.sidebarTagMenu===el.dataset.sidebarTagMenu?null:el.dataset.sidebarTagMenu;state.sidebarTagEditor=null;render();}));
      document.querySelectorAll("[data-edit-sidebar-tag]").forEach(el=>el.addEventListener("click",()=>{state.sidebarTagEditor={mode:el.dataset.editSidebarTag,tags:[state.sidebarTagMenu]};render();requestAnimationFrame(()=>document.querySelector("#tag-rename-input")?.select());}));
      document.querySelectorAll("[data-close-tag-manager]").forEach(el=>el.addEventListener("click",()=>{state.sidebarTagEditor=null;state.sidebarTagMenu=null;render();}));
      document.querySelector("[data-save-tag-name]")?.addEventListener("click",()=>renameSidebarTag(state.sidebarTagEditor.tags[0],document.querySelector("#tag-rename-input").value));
      document.querySelector("#tag-rename-input")?.addEventListener("keydown",event=>{if(event.key==="Enter")renameSidebarTag(state.sidebarTagEditor.tags[0],event.target.value);});
      document.querySelectorAll("[data-set-tag-color]").forEach(el=>el.addEventListener("click",()=>{tagColors[state.sidebarTagEditor.tags[0]]=el.dataset.setTagColor;persistTagSettings();state.sidebarTagEditor=null;state.sidebarTagMenu=null;render();}));
      document.querySelector("[data-bulk-remove-tags]")?.addEventListener("click",()=>{state.sidebarTagEditor={mode:"delete",tags:[...state.selectedSidebarTags]};state.sidebarTagMenu=null;render();});
      document.querySelector("[data-clear-sidebar-selection]")?.addEventListener("click",()=>{state.selectedSidebarTags.clear();state.lastSidebarTagIndex=null;render();});
      document.querySelector("[data-remove-sidebar-tags]")?.addEventListener("click",()=>removeSidebarTags(state.sidebarTagEditor.tags));
      document.querySelectorAll("[data-sidebar-tag-row]").forEach(el=>{el.addEventListener("dragstart",event=>{event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",el.dataset.sidebarTagRow);});el.addEventListener("dragover",event=>{event.preventDefault();el.classList.add("drag-over");});el.addEventListener("dragleave",()=>el.classList.remove("drag-over"));el.addEventListener("drop",event=>{event.preventDefault();const source=event.dataTransfer.getData("text/plain"),target=el.dataset.sidebarTagRow;el.classList.remove("drag-over");if(!source||source===target)return;const from=tagCatalog.findIndex(item=>item.tag===source),to=tagCatalog.findIndex(item=>item.tag===target);if(from<0||to<0)return;const [moved]=tagCatalog.splice(from,1);tagCatalog.splice(to,0,moved);tagOrder=tagCatalog.map(item=>item.tag);persistTagSettings();render();});});
      document.querySelector("[data-sort-recent]")?.addEventListener("click",()=>{state.sortRecent=!state.sortRecent;render();});
      document.querySelectorAll("[data-gallery-mode]").forEach(el=>el.addEventListener("click",()=>{state.galleryMode=el.dataset.galleryMode;render();requestAnimationFrame(()=>document.querySelector(`[data-gallery-mode="${state.galleryMode}"]`)?.focus());}));
      document.querySelectorAll("[data-id]").forEach(el=>el.addEventListener("click",event=>{if(event.target.closest("[data-select]"))return;state.activeId=el.dataset.id;state.activeNoteId=el.dataset.id;state.selected=new Set([el.dataset.id]);if(state.inspectorMode==="closed")state.inspectorMode="floating";state.tagPickerOpen=false;render();}));
      document.querySelectorAll("[data-select]").forEach(el=>el.addEventListener("click",event=>{event.stopPropagation();const id=el.dataset.select;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);state.activeId=id;state.activeNoteId=id;state.lastAction="";if(state.selected.size&&state.inspectorMode==="closed")state.inspectorMode="floating";else if(!state.selected.size&&state.inspectorMode!=="docked")state.inspectorMode="closed";state.tagPickerOpen=false;state.tagPickerPosition=null;render();}));
      const search=document.querySelector("#search");search?.addEventListener("focus",()=>{if(!state.searchOpen){state.searchOpen=true;render();requestAnimationFrame(()=>document.querySelector("#search")?.focus());}});search?.addEventListener("input",event=>{state.query=event.target.value;state.searchOpen=true;const cursor=event.target.selectionStart;render();const input=document.querySelector("#search");input?.focus();input?.setSelectionRange(cursor,cursor);});
      document.querySelectorAll("[data-search-tag]").forEach(el=>el.addEventListener("click",()=>{state.query=el.dataset.searchTag;state.searchOpen=false;render();}));
      document.querySelector("#theme")?.addEventListener("click",()=>{state.theme=state.theme==="light"?"dark":"light";applyTheme();render();requestAnimationFrame(()=>document.querySelector("#theme")?.focus());});
      document.querySelector("[data-toggle-tag-picker]")?.addEventListener("click",()=>{state.tagPickerOpen=!state.tagPickerOpen;state.tagPickerPosition=null;state.lastAction="";render();requestAnimationFrame(()=>document.querySelector("#tag-picker-search")?.focus());});
      document.querySelectorAll("[data-close-tag-picker]").forEach(el=>el.addEventListener("click",()=>{state.tagPickerOpen=false;state.tagQuery="";state.tagPickerPosition=null;render();requestAnimationFrame(()=>document.querySelector("[data-toggle-tag-picker]")?.focus());}));
      const tagSearch=document.querySelector("#tag-picker-search");tagSearch?.addEventListener("input",event=>{state.tagQuery=event.target.value;const cursor=event.target.selectionStart;render();const input=document.querySelector("#tag-picker-search");input?.focus();input?.setSelectionRange(cursor,cursor);});tagSearch?.addEventListener("keydown",event=>{if(event.key==="ArrowDown"){event.preventDefault();document.querySelector("[data-apply-tag],[data-create-tag]")?.focus();}if(event.key==="Escape"){event.preventDefault();state.tagPickerOpen=false;render();requestAnimationFrame(()=>document.querySelector("[data-toggle-tag-picker]")?.focus());}});
      document.querySelectorAll("[data-apply-tag]").forEach(el=>el.addEventListener("click",()=>applyTag(el.dataset.applyTag)));document.querySelectorAll("[data-create-tag]").forEach(el=>el.addEventListener("click",()=>applyTag(el.dataset.createTag)));
      document.querySelectorAll("[data-remove-common-tag]").forEach(el=>el.addEventListener("click",()=>removeCommonTag(el.dataset.removeCommonTag)));
      document.querySelectorAll("[data-note-id]").forEach(el=>{const preview=()=>{const note=records.find(item=>item.id===el.dataset.noteId),editor=document.querySelector("[data-note-editor]");if(!note||!editor)return;document.querySelector("[data-note-full-title]").textContent=note.title;editor.value=note.note;editor.dataset.noteEditor=note.id;editor.name=`note-${note.id}`;editor.setAttribute("aria-label",`Edit note for ${note.title}`);};el.addEventListener("mouseenter",preview);el.addEventListener("focus",preview);el.addEventListener("click",()=>{state.activeNoteId=el.dataset.noteId;render();});});
      document.querySelectorAll("[data-note-editor]").forEach(editor=>editor.addEventListener("input",event=>{const note=records.find(item=>item.id===event.target.dataset.noteEditor);if(!note)return;note.note=event.target.value;persistRecord(note);const preview=document.querySelector(`[data-note-id="${note.id}"] span`);if(preview)preview.textContent=note.note||"No note yet";}));
      document.querySelector("[data-clear-selection]")?.addEventListener("click",()=>{state.selected.clear();state.lastAction="";if(state.inspectorMode!=="docked")state.inspectorMode="closed";state.tagPickerOpen=false;state.tagPickerPosition=null;render();});
      document.querySelector("[data-toggle-dock]")?.addEventListener("click",()=>{state.inspectorMode=state.inspectorMode==="docked"?(state.selected.size?"floating":"closed"):"docked";state.inspectorPosition=null;render();});
      document.querySelector("[data-close-inspector]")?.addEventListener("click",()=>{state.inspectorMode="closed";render();});
      bindInspectorDrag();
      positionTagPicker();
      bindTagPickerDrag();
    }
    function focusSnapshot(){const element=document.activeElement;if(!element||element===document.body)return null;return{id:element.id||null,noteId:element.dataset?.noteEditor||null,start:element.selectionStart,end:element.selectionEnd};}
    function restoreFocus(snapshot){if(!snapshot)return;const element=snapshot.id?document.getElementById(snapshot.id):snapshot.noteId?document.querySelector(`[data-note-editor="${snapshot.noteId}"]`):null;element?.focus();if(typeof snapshot.start==="number")element?.setSelectionRange(snapshot.start,snapshot.end);}
    async function loadLibrary(preserveFocus=false){const focus=preserveFocus?focusSnapshot():null;const library=await PinRefStore.readLibrary();const selectedIds=new Set(state.selected);records.splice(0,records.length,...Object.values(library.records).map(recordFromStored));tagColors={...library.tagColors};tagOrder=[...library.tagOrder];rebuildTagCatalog();state.selected=new Set([...selectedIds].filter(id=>records.some(record=>record.id===id)));if(state.activeId&&!records.some(record=>record.id===state.activeId))state.activeId=null;if(state.activeNoteId&&!records.some(record=>record.id===state.activeNoteId))state.activeNoteId=null;if(state.filter!=="All"&&!['Recent','Untagged','Trash'].includes(state.filter)&&!tagCatalog.some(item=>item.tag===state.filter))state.filter="All";render();restoreFocus(focus);}
    document.querySelector("#reload-dashboard-metadata")?.addEventListener("click",reloadSelectedMetadata);
    chrome.runtime.sendMessage({type:"pinref:dashboardReady"}).catch(()=>{});
    applyTheme();loadLibrary();
    chrome.storage.onChanged.addListener((changes,areaName)=>{if(areaName==="local"&&changes[PinRefStore.STORAGE_KEY])loadLibrary(true);});
    compactMedia.addEventListener("change",event=>{state.sidebarOpen=!event.matches;render();});
    document.addEventListener("pointerdown",event=>{if(state.searchOpen&&!event.target.closest(".search-box")){setTimeout(()=>{if(state.searchOpen){state.searchOpen=false;render();}},0);}},true);
    document.addEventListener("keydown",event=>{const editing=event.target.matches("input,textarea,[contenteditable=true]");if(!editing&&(event.key==="/"||((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"))){event.preventDefault();document.querySelector("#search")?.focus();}if(event.key==="Escape"){if(state.sidebarTagEditor||state.sidebarTagMenu){state.sidebarTagEditor=null;state.sidebarTagMenu=null;}else if(state.tagPickerOpen){state.tagPickerOpen=false;state.tagQuery="";state.tagPickerPosition=null;}else if(state.searchOpen)state.searchOpen=false;else if(!editing&&state.selected.size){state.selected.clear();if(state.inspectorMode!=="docked")state.inspectorMode="closed";}render();}});
